language: java

jdk:
  - oraclejdk8

env:
  - ORG_GRADLE_PROJECT_CI=true

cache:
  directories:
  - $HOME/.gradle

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push w4tson/blackfriar;
    fi