sudo: required

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle

env:
  - ORG_GRADLE_PROJECT_CI=true

services:
  - docker

script:
  - ./gradlew build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push w4tson/blackfriar;
    fi